# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ vehicle-spring-dao ]
  pull_request:
    branches: [ vehicle-spring-dao ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://localhost:9090"
        user: "technohunk100"
        token: ${{ secrets.TOKEN }}
        job: "Vehicle_Project"
